---
title: "R Markdown and Leaflet assignment"
author: "CK"
date: "26 April 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(leaflet)
```

## A map of 10 most global liveable cities - 2018 ranking 

Global Liveability Ranking was obtained from 
[Wikipedia](https://en.wikipedia.org/wiki/Global_Liveability_Ranking#2018_results). 
Latitude and Longitude of center of these cities where obtained from <https://www.latlong.net/> 

```{r}
citiesLatLong <- data.frame( lat = c(48.208176, -37.813629, 34.693737, 51.048615, -33.868820,
                                     49.282730, 35.689487, 43.653225, 55.676098, -34.928497), 
                             lng = c(16.373819, 144.963058, 135.502167, -114.070847, 151.209290,
                                   -123.120735, 139.691711, -79.383186, 12.568337, 138.600739))

icons <- awesomeIcons(text = c(seq(1,10,1)))
popups <- c("1. Vienna, Austria", "2. Melbourne, Australia", "3. Osaka, Japan", "4. Calgary, Canada", 
            "5. Sydney, Australia", "6. Vancouver, Canada", "7. Tokyo, Japan", "8. Toronto, Canada", 
            "9. Copenhagen, Denmark", "10. Adelaide, Australia")
```

```{r, fig.align='center'}                             
citiesLatLong %>% leaflet() %>% addTiles() %>% addAwesomeMarkers(popup = popups ,icon=icons,clusterOptions = markerClusterOptions())
```
